[workspace]
resolver = "3"
members = [
    "crate/realize-cmd",
    "crate/realize-control",
    "crate/realize-daemon",
    "crate/realize-core",
    "crate/realize-network",
    "crate/realize-storage",
    "crate/realize-types",
]
